/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface": "#131313",
          "on-surface": "#e2e2e2",
          "on-primary": "#680011",
          "on-error-container": "#ffdad6",
          "on-tertiary-container": "#e2e3e3",
          "inverse-surface": "#e2e2e2",
          "tertiary-fixed-dim": "#c6c6c7",
          "on-surface-variant": "#e5bdbb",
          "on-secondary": "#2f3131",
          "on-primary-fixed-variant": "#92001c",
          "primary-fixed-dim": "#ffb3b1",
          "tertiary-container": "#636565",
          "outline-variant": "#5c403f",
          "on-tertiary": "#2f3131",
          "surface-variant": "#353535",
          "secondary-fixed": "#e3e2e2",
          "inverse-on-surface": "#303030",
          "on-error": "#690005",
          "surface-tint": "#ffb3b1",
          "inverse-primary": "#bf0229",
          "primary-container": "#c8102e",
          "on-secondary-fixed": "#1a1c1c",
          "on-secondary-fixed-variant": "#464747",
          "on-secondary-container": "#b8b8b8",
          "tertiary": "#c6c6c7",
          "on-background": "#e2e2e2",
          "secondary-container": "#484949",
          "secondary": "#c6c6c6",
          "surface-container-lowest": "#0e0e0e",
          "surface-container": "#1f1f1f",
          "on-primary-fixed": "#410007",
          "primary": "#ffb3b1",
          "tertiary-fixed": "#e2e2e2",
          "surface-container-low": "#1b1b1b",
          "surface-dim": "#131313",
          "background": "#131313",
          "surface-bright": "#393939",
          "error": "#ffb4ab",
          "error-container": "#93000a",
          "outline": "#ac8887",
          "secondary-fixed-dim": "#c6c6c6",
          "on-tertiary-fixed-variant": "#454747",
          "on-primary-container": "#ffdad8",
          "on-tertiary-fixed": "#1a1c1c",
          "surface-container-highest": "#353535",
          "primary-fixed": "#ffdad8",
          "surface-container-high": "#2a2a2a"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "unit": "4px",
          "gutter": "24px",
          "margin-lg": "64px",
          "margin-md": "32px",
          "margin-sm": "16px",
          "container-max": "1200px"
      },
      "fontFamily": {
          "label-caps": ["Space Grotesk", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "mono-data": ["Inter", "sans-serif"],
          "headline-xl": ["Space Grotesk", "sans-serif"],
          "headline-lg": ["Space Grotesk", "sans-serif"],
          "headline-md": ["Space Grotesk", "sans-serif"]
      },
      "fontSize": {
          "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "mono-data": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}],
          "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
