/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface": "#0A0A0A",
          "on-surface": "#FFFFFF",
          "on-primary": "#FFFFFF",
          "on-error-container": "#FFFFFF",
          "on-tertiary-container": "#FFFFFF",
          "inverse-surface": "#FFFFFF",
          "tertiary-fixed-dim": "#CCCCCC",
          "on-surface-variant": "#D1D5DB",
          "on-secondary": "#FFFFFF",
          "on-primary-fixed-variant": "#C8102E",
          "primary-fixed-dim": "#C8102E",
          "tertiary-container": "#1F1F1F",
          "outline-variant": "#333333",
          "on-tertiary": "#FFFFFF",
          "surface-variant": "#1A1A1A",
          "secondary-fixed": "#E5E5E5",
          "inverse-on-surface": "#000000",
          "on-error": "#FFFFFF",
          "surface-tint": "#C8102E",
          "inverse-primary": "#C8102E",
          "primary-container": "#C8102E",
          "on-secondary-fixed": "#000000",
          "on-secondary-fixed-variant": "#888888",
          "on-secondary-container": "#CCCCCC",
          "tertiary": "#CCCCCC",
          "on-background": "#FFFFFF",
          "secondary-container": "#222222",
          "secondary": "#CCCCCC",
          "surface-container-lowest": "#000000",
          "surface-container": "#111111",
          "on-primary-fixed": "#C8102E",
          "primary": "#C8102E",
          "tertiary-fixed": "#FFFFFF",
          "surface-container-low": "#0D0D0D",
          "surface-dim": "#050505",
          "background": "#000000",
          "surface-bright": "#222222",
          "error": "#C8102E",
          "error-container": "#C8102E",
          "outline": "#444444",
          "secondary-fixed-dim": "#CCCCCC",
          "on-tertiary-fixed-variant": "#888888",
          "on-primary-container": "#FFFFFF",
          "on-tertiary-fixed": "#000000",
          "surface-container-highest": "#222222",
          "primary-fixed": "#C8102E",
          "surface-container-high": "#181818"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "unit": "4px",
          "gutter": "24px",
          "margin-lg": "64px",
          "margin-md": "32px",
          "margin-sm": "16px",
          "container-max": "1200px"
      },
      "fontFamily": {
          "label-caps": ["Soria", "Plus Jakarta Sans", "sans-serif"],
          "body-md": ["Soria", "Plus Jakarta Sans", "sans-serif"],
          "headline-lg-mobile": ["Playfair Display", "Soria", "serif"],
          "body-lg": ["Soria", "Plus Jakarta Sans", "sans-serif"],
          "mono-data": ["Soria", "Plus Jakarta Sans", "sans-serif"],
          "headline-xl": ["Playfair Display", "Soria", "serif"],
          "headline-lg": ["Playfair Display", "Soria", "serif"],
          "headline-md": ["Playfair Display", "Soria", "serif"]
      },
      "fontSize": {
          "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "mono-data": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}],
          "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
